### ISSUE TITLE
Call Lineage's Calculation Option and Display it's Return

### ISSUE THREAD

**Issue by peterbusche** [cs481-ekh/s24--1#110]
#105

**Comment by peterbusche** [comment]
[t:120] wrote call to calculate options for relatedness and lineages. Read code to figure out what everything does now

**Comment by samuelflock** [comment]
This was much quicker because I used code from #111 

I also implemented a Cursor change because the function takes a while. There seems to be a bug so I'll make a new bug in the backlog for it.

{t:60}
