### ISSUE TITLE
Set up Editor panel dropdown functionality

### ISSUE THREAD

**Issue by zanemiller148** [cs481-ekh/s24--1#126]
Reference #21

**Comment by samuelflock** [comment]
Accidentally Pushed to Main at start, but reverted that change.

Checkbox Button works the first time, but not after the first cycle. I think it has to do with indexing problems.

The deleted row exists and can now be used to populate Dropdowns

{t:90}

**Comment by samuelflock** [comment]
Worked on Column Name Changes.
Having Problems with differing array shapes

{t:40}

**Comment by samuelflock** [comment]
Completed Task:
First Row Header Checkbox works,
Dropdown Menus update from checkbox

{t:45}
