### ISSUE TITLE
Github Actions Bug

### ISSUE THREAD

**Issue by samuelflock** [cs481-ekh/s24--1#80]
The github actions do not perform correctly. It seems to be seg faulting when the program runs.

**To Reproduce**
1. Create Pull Request
(Any new commits will cause same problem)

**Expected behavior**
The actions should be able to run correctly and cause no errors. It should also fail as necessary.

**Additional context**
The problem only exists on Github Actions. If you run the program on a local machine, there is no seg fault.

**Comment by samuelflock** [comment]
{t:30}

**Comment by zanemiller148** [comment]
Fixing time allocation.

Sprint 3.

{t:120}
