### ISSUE TITLE
PORT: Descent.py 

### ISSUE THREAD

**Issue by peterbusche** [cs481-ekh/s24--1#83]
No user story.
  Copy the old version of Descent.py
  Create strong documentation for every class and method in this file.
  Comment out any functionality that doesn't work.
  Only worry about basic GUI functionality, get it working as similar to old GUI as possible.

**Comment by peterbusche** [comment]
-Stubbed out every class and function in the GUI. Corrected functionality and organization for basic GUI so it matches old code. made sure old code is visible for when we start updating pieces and parts.

[t:120]

**Comment by peterbusche** [comment]
[t:240] Updated all functions in the classes: MyFrame, Notebook, Panel, EditorPanel and  MyApp. Documented all these functions as I went along. Made sure they worked with dependency files. Many still need to be tested.

**Comment by samuelflock** [comment]
{t:20}
