### ISSUE TITLE
PORT: CustomDataTable.py

### ISSUE THREAD

**Issue by peterbusche** [cs481-ekh/s24--1#84]
No User Story:
   Copy the old version of Descent.py
   Create strong documentation for every class and method in this file.
   Comment out any functionality that doesn't work.

**Comment by peterbusche** [comment]
-Stubbed out every class and function. Left old code that doesn't throw errors as is. Errors were mainly due to old wxPython code, I updated this code so it wouldn't throw errors. Need to test is later to make sure updates work. When we get dependencies working, we can figure out which functionalities to turn ON/OFF to make sure they work. Commented out old code, so it is visible for when we start testing.

[t:60]

**Comment by peterbusche** [comment]
[t:120] went through and made small changes, mainly to wxPython, so classes will work when called by our panels. Wrote some documentation.

**Comment by samuelflock** [comment]
{t:10}
